gloo:
  settings:
    # Only watch 2 specific namespaces for Gloo CRs, which does not include the application namespace(s).
    watchNamespaces:
    - gloo-system
    - gloo-deployments
    # - httpbin
  discovery:
    enabled: false
  gatewayProxies:
    gatewayProxy:
      gatewaySettings:
        accessLoggingService:
          accessLog:
          - fileSink:
              path: /dev/stdout
              stringFormat: ""