apiVersion: gloo.solo.io/v1
kind: Upstream
metadata:
  name: httpbin-httpbin-8000
  namespace: gloo-deployments
spec:
  # discoveryMetadata:
  #   labels:
  #     app: keycloak
  kube:
    selector:
      app: httpbin
    serviceName: httpbin
    serviceNamespace: httpbin
    servicePort: 8000
